# Generated by Django 3.1.7 on 2021-04-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(auto_created=True, verbose_name='user id')),
                ('name', models.CharField(default='dummy', max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('authority', models.IntegerField(verbose_name='authority')),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
            ],
        ),
    ]
