# Generated by Django 3.1.7 on 2021-04-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='movie id')),
                ('name', models.CharField(max_length=40, verbose_name='movie name')),
                ('year', models.IntegerField(verbose_name='released year')),
                ('outline', models.CharField(max_length=100, verbose_name='plot outline')),
                ('cast', models.CharField(max_length=50, verbose_name='principle cast')),
                ('genre', models.CharField(max_length=20, verbose_name='movie genre')),
                ('rates', models.IntegerField(verbose_name='average user rating')),
                ('movie_url', models.CharField(max_length=80, verbose_name='url to official site')),
                ('img_url', models.CharField(max_length=80, verbose_name='url to movie posts')),
                ('reviews_url', models.CharField(max_length=80, verbose_name='url to reviews')),
            ],
        ),
    ]
