# Generated by Django 3.1.7 on 2021-04-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210410_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.TextField(verbose_name='principle cast'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=40, verbose_name='movie genre'),
        ),
    ]
