# Generated by Django 3.1.7 on 2021-04-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210410_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img_url',
            field=models.CharField(max_length=80, null=True, verbose_name='url to movie posts'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='reviews_url',
            field=models.CharField(max_length=80, null=True, verbose_name='url to reviews'),
        ),
    ]
