# Generated by Django 3.1.7 on 2021-04-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    def forwards(apps, schema_editor):
        if schema_editor.connection.alias != 'default':
            return

    # Your migration code goes here
    dependencies = [
        ('movies', '0006_auto_20210410_0424'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
