# Generated by Django 3.1.7 on 2021-04-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='review id')),
                ('user_name', models.CharField(max_length=20, verbose_name='user name')),
                ('movie_id', models.IntegerField(verbose_name='movie id')),
                ('movie_name', models.CharField(max_length=40, verbose_name='movie name')),
                ('rates', models.IntegerField(verbose_name='rates')),
                ('comments', models.CharField(max_length=800, verbose_name='comment')),
                ('comments_img', models.CharField(max_length=80, verbose_name='appendix image')),
            ],
        ),
    ]
