# Generated by Django 3.1.7 on 2021-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210410_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comments_img',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='appendix image'),
        ),
    ]
