# Generated by Django 3.1.7 on 2021-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210410_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='review id'),
        ),
    ]
